### ISSUE TITLE
Fix Dashboard Authorization

### ISSUE THREAD

**Issue by jadenfreude** [adonese/noebs#149]
`/dashboard` API is open without authorization and exposed to the web. This constitutes a major privacy and security flaw in the server, allowing anyone to access, view and download transaction history.

**Comment by adonese** [comment]
Hi Abdelrahman,


Thanks a lot for your great feedback, and I concur with your comments,
dashboard should be *deployed* behind a protected endpoint.

The reason we have done so with noebs is because we really wanted to offer
just the minimum set of services, we want noebs to be less opinionated and
more modular and permissive to its users to use it as they please. k?

However, what do you think? Got any ideas we can work on together?

**Comment by jadenfreude** [comment]
Hello Mohamed!

Before I begin I would like to qualify my message with the fact that I am not a Go developer, and my experience with API in general is very limited.

That being said, if I understood you correctly, you mean the server (specifically the dashboard service) should be deployed behind some sort of firewall or reverse proxy whitelisting the specific application that is _meant_ to communicate with the API. I suppose that is one way to implement it. However, one could theoretically [modify their X-Forwarded headers](https://medium.com/r3d-buck3t/bypass-ip-restrictions-with-burp-suite-fb4c72ec8e9c), essentially spoofing a whitelisted address. I am yet to test this approach though.

On the point that you're designing NOEBS as modular and permissive, I suppose you mean that NOEBS is meant to be inserted into a system and modified for the specific use of the user, not forcing a user to "do it the NOEBS way". I completely agree, but I do not think that securing parts or all of your API is at odds with that goal. It already looks like NOEBS is embracing dockerization. In such a case, my suggestion would be striving to create containerized microservice (similar MySQL and PostgreSQL images), where you use docker-compose and environment variables to define whether the API is open for everyone (a service like that of SolusPay) or open for a specific application (e.g. Sahil). In the latter case, the container will require setting a hostname, username and password for access, and will deploy an internal certbot service for SSL encryption. That way, it can securely plug-n-play as part of any web application.

But I realize that all of the above is a monumental effort that will take months without an active development community. My immediate suggestion is drawing up the future NOEBS architecture (including the internal certbot service, redis server, etc.) then creating a roadmap toward it, which can later be translated into documentation for developers and GitHub projects.

Speaking of documentation, I think the README should outline how one can contribute to it, as it is not yet clear. I would opt to deploy a specialized wiki app for this purpose, like WikiJS or something similar. However, if documentation is to git, the steps to contribution must be clarified.

I have no idea if this would be enough to attract a community for development, but if someone is interested I think NOEBS should be ready to take them. Of course, what I said is merely a reflection of my experience deploying (not developing) web apps, and could be completely incompatible with NOEBS's vision.

**Comment by adonese** [comment]
Hi Abdelrhman,

> Hello Mohamed!
> 
> Before I begin I would like to qualify my message with the fact that I am not a Go developer, and my experience with API in general is very limited.

That's totally fine, don't worry about it!

> That being said, if I understood you correctly, you mean the server (specifically the dashboard service) should be deployed behind some sort of firewall or reverse proxy whitelisting the specific application that is meant to communicate with the API. I suppose that is one way to implement it. However, one could theoretically [modify their X-Forwarded headers](https://medium.com/r3d-buck3t/bypass-ip-restrictions-with-burp-suite-fb4c72ec8e9c), essentially spoofing a whitelisted address. I am yet to test this approach though.
And that's why maybe it is better left to noebs consumers to decide on what security model they want to have? Think about noebs as just the application code, it only just uses payment apis, and it leaves the rest to the consumers to roll out their own solution. I believe protecting /dashboard apis won't be a difficult thing to add to noebs right now, but in doing so we also have to make sure that we can audit, monitor and maintain that. As in, we have to audit whatever security model we decided to add, that's not a trivial task however.

> But I realize that all of the above is a monumental effort that will take months without an active development community. My immediate suggestion is drawing up the future NOEBS architecture (including the internal certbot service, redis server, etc.) then creating a roadmap toward it, which can later be translated into documentation for developers and GitHub projects.
We have that, more or less. The only thing we don't have is very specific, and could be generalized in _deploying noebs_. Maybe we should add a detailed document with recommendation on which good practices one can follow to deploy and secure noebs endpoints.

> Speaking of documentation, I think the README should outline how one can contribute to it, as it is not yet clear. I would opt to deploy a specialized wiki app for this purpose, like WikiJS or something similar. However, if documentation is via git, the steps to contribution must be clarified.

> I have no idea if this would be enough to attract a community for development, but if someone is interested I think NOEBS should be ready to take them. Of course, what I said is merely a reflection of my experience deploying (not developing) web apps, and could be completely incompatible with NOEBS's vision.
I would assume everybody uses github for contributing, the source code is hosted there.

>Edit: I am currently working on implementing a modular Django app that interacts with NOEBS, similar to that of stripe. I believe it will immediately unlock all kinds of web applications that were not deployed in Sudan because of poor e-banking integration.

Looking forward to help you with what i can!

**Comment by jadenfreude** [comment]
Now that you explain the limitation, it makes sense why it's built the way it is.

> We have that, more or less. The only thing we don't have is very specific, and could be generalized in _deploying noebs_. Maybe we should add a detailed document with recommendation on which good practices one can follow to deploy and secure noebs endpoints.

I agree. However, deployment is only the beginning. The documentation can be split into two large sections:
- Getting started (tutorials deploying NOEBS in dev and mock transactions via interacting with the API) 
- Data structure and object documentation 
- API documentation. 

The reason I believe API and object documentation needs work as well is because a lot of the JSON API variables aren't self evident in why they're needed, and some of them are duplicates. As for objects, it will help future developers understand the structure of NOEBS, contribute to it and develop their applications for it. I think I can contribute to the "getting started" tutorials section. Tutorials might not give the community the flexibility they need.

> I would assume everybody uses github for contributing, the source code is hosted there.

For sure, but not every interested developer will set aside the time to digest NOEBS on their own in order to begin contributing. Proper Developer Documentation will help them find exactly the part they're interested in improving without needing to look through the entire codebase. My perspective is one of reducing friction for new contributors. Like I mentioned, I can help with the getting started tutorial(s).
