### ISSUE TITLE
Change noebs registration required fields

### ISSUE THREAD

**Issue by adonese** [adonese/noebs#156]
### Discussed in https://github.com/adonese/noebs/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **adonese** May 23, 2022</sup>
Currently, noebs asks for way too many fields (all required) upon signing up:
- username
- fullname
- password
- password2
- email
- phone_number

We can make that simpler, into two steps form:
First step will include:
- phone_number
- password (password2 will be dropped)

Step 2:
- first_name
- last_name
- address (optional)
- birthdate
- email
- username?

Step 3 (full KYC):
In addition to the above,
- Selfie video
- Selfie video with ID</div>

Do we use @username anywhere in our code?

**Comment by awabrh** [comment]
I think it would be easier to merge the First name & Last name into Full name field
also do we have an endpoint to update the user's info? other than registration

**Comment by adonese** [comment]
No, this is also something we should add as a todo. I will assign it to
myself
