### ISSUE TITLE
Required features for payment link and omni box

### ISSUE THREAD

**Issue by rami3sam** [adonese/noebs#226]
Good morning,
I'd like you to make these api route or expose them through the sdk if they're already made
1- Payment Link
-an api to query the uuid in the deep link's url and get the following info:
User's masked pan
Requested amount
Bonus:
Link's creation date
And a note set by the requestee

-a route to make a purchase by giving it the uuid (or the payment token) and the amount

2-omni box
-An endpoint for querying about if a phone number or a group of phone numbers have tuti accounts 
-An endpoint for doing payments by giving the receiver's phone number and the amount

@adonese @mseltahir

**Comment by adonese** [comment]
In the omnibox, I want to inquire further.

### Scenario 1

Let's say a user have a valid tuti account, I believe the next step would be performing the payment via their tuti account and ignore the cards in its entirety, no? Or, we should as well return back the payment card (the receiving card).

## Scenario 2

If a user doesn't have a valid card (expired for any reason) or their account activation didn't complete, or they don't even have an account, how we you handle this case (for us we will just return a non-200 response)

**Comment by adonese** [comment]
- [ ] an api to query the uuid in the deep link's url and get the following info: User's masked pan, Requested amount, Link's creation date, And a note set by the requestee (masked pan, amount, created_at, note)
- [ ] a route to make a purchase by giving it the uuid (or the payment token) and the amount (awaiting rami's feedback)
- [ ] An endpoint for querying about if a phone number or a group of phone numbers have tuti accounts
- [ ] An endpoint for doing payments by giving the receiver's phone number and the amount

**Comment by mseltahir** [comment]
> * [ ]  an api to query the uuid in the deep link's url and get the following info: User's masked pan, Requested amount, Link's creation date, And a note set by the requestee (masked pan, amount, created_at, note)

We have a couple of options here, we can either modify the `GetPaymentToken` function and generalize it to handle this case also, or we can create a new function with a new endpoint that does this, but I'm not comfortable with the amount of code duplication in the second case. What do you think?

> * [ ]  a route to make a purchase by giving it the uuid (or the payment token) and the amount (awaiting rami's feedback)

The modified new version of `NoebsQuickPayment` by @adonese in 9699861bedc3c1d54d3a900c430f1e234d97e4f6, handles all these cases.

> * [ ]  An endpoint for querying about if a phone number or a group of phone numbers have tuti accounts

I have written this in the `/submit_contacts` endpoint recently integrated in dd77da2635d05315020096fdffe39cbf5f42a78b, I can modify it to send back a sub list of the sent list of contacts that has the contacts that have a Tuti account, which the front-end can use to differentiate contacts.

**Comment by mseltahir** [comment]
> I have written this in the `/submit_contacts` endpoint recently integrated in [dd77da2](https://github.com/adonese/noebs/commit/dd77da2635d05315020096fdffe39cbf5f42a78b), I can modify it to send back a sub list of the sent list of contacts that has the contacts that have a Tuti account, which the front-end can use to differentiate contacts.

After giving it another thought I think this won't be sufficient, since checking if someone is a user or not is required each time in the omnibox. Instead I've implemented a seperate endpoint.

**Comment by mseltahir** [comment]
@rami3sam have you checked that everything is good?

**Comment by mseltahir** [comment]
Rami: all good.
