### ISSUE TITLE
`is_main` is not activated neither working 

### ISSUE THREAD

**Issue by adonese** [adonese/noebs#232]

**Comment by mseltahir** [comment]
I think we should:

1. Set the first card as the main one by default.
2. Provide the ability to change the main card to any card that is registered for the user.
3. Keep the current `User` struct as is (having the main card stored in the `User.Pan` field for convenience but we have to remember to also change it when we change main card).

**Comment by mseltahir** [comment]
>     1. Set the first card as the main one by default.

In 6214b984cc0bda11899ff1124042f9b17ff7de0f, I enabled this in the `/register_with_card` endpoint function. Is there any other place where you think we should modify @adonese?

>     2. Provide the ability to change the main card to any card that is registered for the user.

In 73e39b9a9df5eac24a73c27664f80792fac74575 and 45acc67125dfd05a803f11f1e7bae90c7a6d446c I've added the functionality for this.

**Comment by adonese** [comment]
I recall that would be the only place we trigger it

**Comment by mseltahir** [comment]
Great, we can mark this as resolved.
