### ISSUE TITLE
add websockets for chat features

### ISSUE THREAD

**Issue by adonese** [adonese/noebs#30]
a very awaited feature is to add chat support for our [cashq](https://cashq.soluspay.net). it will help in many regards, but it is really just a nice feature to have a chat enabled in our platforms.

**Comment by adonese** [comment]
@mseltahir we can start from here

**Comment by mseltahir** [comment]
@adonese great, here's a simple echo server for a start: [https://github.com/tutipay/chat-service](chat-service).

I think we need to define the detailed specifications of the chat and the design of the API we're going to expose before we go any further.
