### ISSUE TITLE
missing Libraries or package

### ISSUE THREAD

**Issue by Tayeb-Ali** [adonese/noebs#6]
hello ,
i try test this system on my local machine  
so i see this missing:
 package noebs/dashboard 
and noebs/validations
in .gitignore  you put noebs file or package

**I am not an expert in this language (gO lANG).**

> may can you writ some documentation :) :+1:

**Comment by Tayeb-Ali** [comment]
Well, I hope I could help you ?.
like in code :dagger: ^-*

**Comment by adonese** [comment]
That would definitely be appreciated!

**Comment by adonese** [comment]
I fixed this issue in commit [e481b5a](https://github.com/adonese/noebs/commit/e481b5a58dda9166106cbf26d13bbc9fa3030758). It should be working now!
I will be adding new features in the next upcoming days, stay tuned!

**Comment by adonese** [comment]
If using docker, you might try this (you are in this repo dir)
`docker build -t noebs .`
`docker run -it -p 8080:8080 noebs:latest`
Or, you can also try `docker-compose up` it should work too.

**Comment by Tayeb-Ali** [comment]
yes, i fix the error  by using the containers "Docker"

**Comment by adonese** [comment]
Awesome!
